### ISSUE TITLE
is Mycelite still actively developed and maintained?

### ISSUE THREAD

**Issue by fenicento** [mycelial/mycelite#51]
Hi, it looks like there's no way to access this project's documentation. Is it still being developed / maintained?

**Comment by tbaums** [comment]
Hey @fenicento ! Thanks so much for asking.

Mycelite has been folded into the broader mycelial/mycelial project which is about a million times better. Would love to hear your thoughts if you take it for a spin!

https://github.com/mycelial/mycelial

https://docs.mycelial.com
